import { UsageGuide } from '../shared/tool-guide';
export const ADVANCED_GUIDES: Record<string, Record<string, UsageGuide>> = {
  'regex-tester': {
    match: { input: 'Paste text, enter a JavaScript regex without surrounding / characters, and choose flags such as g for all matches or i to ignore case.', action: 'Click Run tool. Load example fills text, pattern, and flags together.', output: 'Match count, matched text, UTF-16 start/end offsets, numbered captures, and named captures. No matches returns an empty list.', exampleInput: 'Ada 42, Lin 7', exampleFields: { pattern: '\\d+', flags: 'g', replacement: '#' }, exampleOutput: '2 matches: "42" at index 4, "7" at index 12', exampleLabel: 'Example with pattern \\d+ and flag g (output summary)' },
    replace: { input: 'Enter the original text, pattern, flags, and replacement. Use g to replace all matches; $1 inserts the first captured group.', action: 'Choose Replace matches, then Run tool. An empty replacement removes matches.', output: 'The text after JavaScript regex replacement. The source editor is preserved. Expensive patterns stop after three seconds.', exampleInput: 'Ada 42, Lin 7', exampleFields: { pattern: '\\d+', flags: 'g', replacement: '#' }, exampleOutput: 'Ada #, Lin #', exampleLabel: 'Example with pattern \\d+, flag g, replacement #' },
  },
  'json-diff': { compare: { input: 'Paste the original JSON in the first editor and the updated JSON in the second. Each must be one valid JSON value.', action: 'Click Run tool. Object field order is ignored; arrays compare items at the same index.', output: 'An equal flag and a list of added, removed, or changed values with their paths. This is a comparison report, not an executable patch.', exampleInput: '{"name":"Ada","active":false}', exampleFields: { comparison: '{"name":"Ada","active":true}' }, exampleOutput: '{"equal":false,"changes":[{"kind":"changed","path":"/active","before":false,"after":true}]}' } },
  'text-diff': { compare: { input: 'Paste the original and updated text in their respective editors. Empty text is allowed.', action: 'Click Run tool to compare exact lines, including whitespace and line endings.', output: 'Ordered chunks labeled unchanged, removed, or added, with text and line counts. Equal text reports equal: true.', exampleInput: 'hello\nold\n', exampleFields: { comparison: 'hello\nnew\n' }, exampleOutput: 'unchanged: "hello\\n"\nremoved: "old\\n"\nadded: "new\\n"', exampleLabel: 'Example (output summary)' } },
  'json-lines': {
    'to-array': { input: 'Paste one JSON value per line. Interior blank lines are invalid; one final newline is allowed.', action: 'Choose JSON Lines → array and click Run tool. Errors identify the record line.', output: 'A formatted JSON array containing all records in order. Strings, numbers, objects, arrays, and null are supported.', exampleInput: '{"id":1}\n{"id":2}', exampleOutput: '[{"id":1},{"id":2}]' },
    'to-lines': { input: 'Paste a JSON array containing the records to export.', action: 'Choose JSON array → lines and click Run tool.', output: 'One compact JSON value per item, separated by LF. Newlines within strings remain escaped. An empty array produces empty output.', exampleInput: '[{"id":1},{"id":2}]', exampleOutput: '{"id":1}\n{"id":2}' },
  },
  'json-flatten': {
    flatten: { input: 'Paste a JSON document, including any nested objects or arrays.', action: 'Choose Flatten to path entries and click Run tool.', output: 'An array of path/value entries. String segments are object keys; numeric segments are array indexes. Empty objects and arrays remain values, so Restore JSON can recover the structure.', exampleInput: '{"users":[{"name":"Ada"}]}', exampleOutput: '[{"path":["users",0,"name"],"value":"Ada"}]' },
    unflatten: { input: 'Paste path/value entries produced by this tool. Paths must be arrays of strings or numeric indexes; values must be primitive or empty containers.', action: 'Choose Restore JSON and click Run tool. Duplicate, conflicting, mixed, or sparse paths show an error.', output: 'The reconstructed JSON document. A path of [] identifies the root value. Numeric object keys must be strings, such as "0", rather than numeric indexes.', exampleInput: '[{"path":["users",0,"name"],"value":"Ada"}]', exampleOutput: '{"users":[{"name":"Ada"}]}' },
  },
  'html-entities': {
    encode: { input: 'Type text containing characters such as &, <, >, quotes, or non-ASCII characters.', action: 'Choose Encode HTML entities and click Run tool.', output: 'Text using HTML character references where needed. Copy the source into the appropriate HTML text context.', exampleInput: '<b>A & B</b>', exampleOutput: '&lt;b&gt;A &amp; B&lt;/b&gt;' },
    decode: { input: 'Paste valid named or numeric HTML references, including their semicolons.', action: 'Choose Decode HTML entities and click Run tool.', output: 'Decoded text shown literally. Any HTML tags remain text in this app; decoding does not make arbitrary HTML safe to render elsewhere.', exampleInput: '&lt;b&gt;A &amp; B&lt;/b&gt;', exampleOutput: '<b>A & B</b>' },
  },
  'json-string': {
    escape: { input: 'Paste ordinary text, including quotes, tabs, or line breaks.', action: 'Choose Escape as JSON string and click Run tool.', output: 'A complete quoted JSON string with special characters escaped, ready to use as a JSON value.', exampleInput: 'Hello "Ada"\nWelcome', exampleOutput: '"Hello \\"Ada\\"\\nWelcome"' },
    unescape: { input: 'Paste one JSON string with its surrounding double quotes and valid escapes.', action: 'Choose Unescape JSON string and click Run tool.', output: 'The original text with escaped quotes and line breaks restored. Objects, numbers, and malformed strings are rejected.', exampleInput: '"Hello \\"Ada\\"\\nWelcome"', exampleOutput: 'Hello "Ada"\nWelcome' },
  },
  'text-hex': {
    encode: { input: 'Enter valid Unicode text. Emoji and other languages are supported.', action: 'Choose Text → hex bytes and click Run tool.', output: 'Lowercase hexadecimal UTF-8 byte pairs separated by spaces. This is the text encoding, not a hash.', exampleInput: 'Hi 👋', exampleOutput: '48 69 20 f0 9f 91 8b' },
    decode: { input: 'Paste hexadecimal byte pairs, with optional whitespace and no 0x prefixes.', action: 'Choose Hex bytes → text and click Run tool.', output: 'Decoded UTF-8 text. Odd digits, invalid hex, and bytes that are not valid UTF-8 produce errors.', exampleInput: '48 69 20 f0 9f 91 8b', exampleOutput: 'Hi 👋' },
  },
  'unicode-inspector': {
    inspect: { input: 'Paste up to 1,000 Unicode code points to inspect.', action: 'Choose Inspect characters and click Run tool.', output: 'Code-point labels, UTF-16 offsets, UTF-8 hex bytes, and counts. A visible character can contain several code points; an emoji can use several UTF-16 units.', exampleInput: 'A👋', exampleOutput: 'U+0041 → 41, offset 0\nU+1F44B → f0 9f 91 8b, offset 1', exampleLabel: 'Example (output summary)' },
    ...Object.fromEntries(['NFC', 'NFD', 'NFKC', 'NFKD'].map(mode => [mode, {
      input: 'Enter Unicode text to normalize. Combining marks may look identical before and after normalization.', action: `Choose Normalize ${mode} and click Run tool.`, output: `${mode} normalized text. Use Inspect characters afterward to compare code points. Compatibility forms may change character distinctions.`, exampleInput: mode.startsWith('NFK') ? 'Ａ café' : 'cafe\u0301', exampleOutput: (mode.startsWith('NFK') ? 'Ａ café' : 'cafe\u0301').normalize(mode as 'NFC'),
    }])),
  },
  'line-endings': {
    inspect: { input: 'Enter text or load the mixed-newline example. Browser textareas may normalize pasted newlines.', action: 'Choose Inspect line endings and click Run tool.', output: 'Separate CRLF, lone LF, and lone CR counts, plus whether the text begins with a Unicode BOM.', exampleInput: 'first\r\nsecond\nthird\r', exampleOutput: '{"crlf":1,"lf":1,"cr":1,"leadingBom":false}' },
    ...Object.fromEntries([['lf', '\n', 'LF'], ['crlf', '\r\n', 'CRLF'], ['cr', '\r', 'CR']].map(([mode, newline, name]) => [mode, {
      input: 'Enter text with any mix of CRLF, LF, or CR line endings.', action: `Choose Convert to ${name}, run the tool, then Copy result to preserve the generated line-ending bytes.`, output: `Text with all line breaks normalized to ${name}. A final newline is preserved if present. The on-screen textarea may display line endings uniformly.`, exampleInput: 'first\r\nsecond\n', exampleOutput: `first${newline}second${newline}`,
    }])),
    'strip-bom': { input: 'Enter text that may begin with the invisible U+FEFF byte-order-mark character.', action: 'Choose Remove leading BOM and click Run tool.', output: 'Text with at most one leading BOM removed. Other characters and line breaks stay unchanged.', exampleInput: '\uFEFFhello', exampleOutput: 'hello' },
  },
  'password-generator': Object.fromEntries(['mixed', 'alphanumeric'].map(mode => [mode, {
    input: 'Enter a whole-number length from 8 to 128. The default is 24 characters.', action: `Choose ${mode === 'mixed' ? 'Letters, digits & symbols' : 'Letters & digits'}, then Run tool. Each run generates a new password.`, output: 'One randomly generated password of the requested length. Your result will differ from this example. Passwords are never saved by this tool.', exampleInput: '24', exampleOutput: mode === 'mixed' ? '7k!pA2$zQ9#mB4@xR6&vN8?c' : '7kpA2zQ9mB4xR6vN8cT3sH5w', exampleLabel: 'Illustrative example; do not reuse this password',
  }])),
  'slug-generator': { generate: { input: 'Enter a title, phrase, or name to use in a URL path.', action: 'Click Run tool. Decomposable accents are removed and punctuation becomes hyphens.', output: 'A lowercase slug containing Unicode letters, numbers, and single hyphens. Non-Latin letters are preserved; this tool does not ensure uniqueness.', exampleInput: 'Café & API: Hello, World!', exampleOutput: 'cafe-api-hello-world' } },
};
