import type { Configuration } from './utility-config';
export const ADVANCED_CONFIG: Record<string, Configuration> = {
  'regex-tester': { label: 'Text to search', note: 'JavaScript regular expressions, with UTF-16 offsets. Enter a pattern without / delimiters and optional gimsuy flags. At most 500 matches; 3-second worker limit. Replacement uses JavaScript $&, $1, and named-group syntax. Text and captured groups are displayed as data.', modes: [{ value: 'match', label: 'Find matches' }, { value: 'replace', label: 'Replace matches' }], fields: [{ key: 'pattern', label: 'Regular expression', initial: '\\b\\w+\\b', maxLength: 1000 }, { key: 'flags', label: 'Regex flags', initial: 'g', maxLength: 6 }, { key: 'replacement', label: 'Replacement (replace mode)', initial: '', maxLength: 2000 }] },
  'json-diff': { label: 'Original JSON', note: 'Compares parsed values; object key order is ignored, arrays compare by index. Results describe added, removed, or changed values using escaped pointer paths; an empty path means the root. Up to 500 changes. No merging or patch application.', modes: [{ value: 'compare', label: 'Compare JSON' }], fields: [{ key: 'comparison', label: 'Updated JSON', initial: '', multiline: true, maxLength: 100000 }] },
  'text-diff': { label: 'Original text', note: 'Line-by-line comparison preserving whitespace, case, CRLF, and final-newline differences. Outputs ordered added/removed/unchanged chunks. Complex comparisons stop with an error; a worker keeps the page responsive.', modes: [{ value: 'compare', label: 'Compare text' }], fields: [{ key: 'comparison', label: 'Updated text', initial: '', multiline: true, maxLength: 100000 }] },
  'json-lines': { label: 'JSON Lines or JSON array', note: 'One complete JSON value per line, up to 5,000 records. Blank interior lines are invalid; one final newline is allowed. Array export writes compact JSON per item. Duplicate keys and unsafe integers are rejected by the shared JSON parser.', modes: [{ value: 'to-array', label: 'JSON Lines → array' }, { value: 'to-lines', label: 'JSON array → lines' }] },
  'json-flatten': { label: 'JSON document or path entries', note: 'Flattening produces path/value entries: strings identify object keys, numbers identify array indexes. This format preserves dots, empty keys, numeric object keys, empty containers, and root values. At most 5,000 leaves and 64 path segments; conflicting and sparse paths are rejected.', modes: [{ value: 'flatten', label: 'Flatten to path entries' }, { value: 'unflatten', label: 'Restore JSON' }] },
  'html-entities': { label: 'Text or HTML entities', note: 'Encodes or decodes named and numeric HTML entities in text context. Strict decoding requires valid entity syntax. The result is text only; decoding is not HTML sanitization and this tool never renders the output.', modes: [{ value: 'encode', label: 'Encode HTML entities' }, { value: 'decode', label: 'Decode HTML entities' }] },
  'json-string': { label: 'Text or JSON string', note: 'Escape produces a complete JSON string including outer quotes. Unescape expects exactly one quoted JSON string. This handles JSON string syntax; it is not a general JavaScript, SQL, or shell escaper.', modes: [{ value: 'escape', label: 'Escape as JSON string' }, { value: 'unescape', label: 'Unescape JSON string' }] },
  'text-hex': { label: 'UTF-8 text or hex bytes', note: 'Encode text as hexadecimal UTF-8 bytes, or decode byte pairs to text. Whitespace between pairs is accepted; 0x prefixes are not. Invalid UTF-8 and unpaired surrogates are rejected. A leading Unicode BOM is preserved.', modes: [{ value: 'encode', label: 'Text → hex bytes' }, { value: 'decode', label: 'Hex bytes → text' }] },
  'unicode-inspector': { label: 'Unicode text', note: 'Inspect up to 1,000 code points: code-point labels, UTF-16 offsets, UTF-8 bytes, and grapheme counts. Normalization accepts the usual input limit and changes representation; NFKC/NFKD also fold compatibility forms. Character names are not included.', modes: [{ value: 'inspect', label: 'Inspect characters' }, ...['NFC', 'NFD', 'NFKC', 'NFKD'].map(value => ({ value, label: `Normalize ${value}` }))] },
  'line-endings': { label: 'Text with line endings', note: 'Inspect or normalize CRLF, LF, and CR, or remove one leading Unicode BOM. Conversion preserves whether a final line break exists. Textareas may normalize pasted line endings; Load example and Copy result preserve the underlying generated value.', modes: [{ value: 'inspect', label: 'Inspect line endings' }, { value: 'lf', label: 'Convert to LF' }, { value: 'crlf', label: 'Convert to CRLF' }, { value: 'cr', label: 'Convert to CR' }, { value: 'strip-bom', label: 'Remove leading BOM' }] },
  'password-generator': { label: 'Password length', inputType: 'number', initial: '24', min: 8, max: 128, note: 'Generate one random password of 8–128 characters using browser cryptographic randomness and unbiased character selection. Mixed uses letters, digits, and symbols; alphanumeric uses letters and digits. Character classes are not guaranteed in each result. Nothing is stored or transmitted.', modes: [{ value: 'mixed', label: 'Letters, digits & symbols' }, { value: 'alphanumeric', label: 'Letters & digits' }] },
  'slug-generator': { label: 'Text for a URL slug', note: 'Lowercases text, removes decomposable combining accents, and joins letters/numbers with hyphens. Non-Latin letters remain Unicode; this is not transliteration or guaranteed uniqueness. Encode the slug as a URL component when needed.', modes: [{ value: 'generate', label: 'Generate slug' }] },
};
