server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8082}
  error:
    include-message: never
    include-stacktrace: never
spring:
  application:
    name: tools-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-trailing-tokens: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
